export interface Bank {
    name: string;
    slug: string;
    code: string;
    ussd: string;
    logo: string;
    address: string;
}

const { npm_package_version: version } = process.env;
const baseUrl = `https://cdn.jsdelivr.net/npm/banks-ng@${version}/dist/`;

export const banks: Bank[] = [
    {
    name: 'Abbey Mortgage Bank',
    slug: 'abbey-mortgage-bank',
    code: '801',
    ussd: '*5103#',
    logo: `${baseUrl}/abbey-mortgage-bank.png`,
    address: 'No 23 Karimu Kotun Street Victoria Island, Lagos, Nigeria',
  },
  {
    name: 'ABOVE ONLY MFB',
    slug: 'AOM',
    code: '51204',
    ussd: '*540*283*0#',
    logo: `${baseUrl}/above-only-mfb.png`,
    address: '1 University Way, Benson Idahosa, University, Ugbor GRA Benin City',
  },
  {
    name: 'Access Bank',
    slug: 'access-bank',
    code: '044',
    ussd: '*901#',
    logo: `${baseUrl}/access-bank.png`,
    address: '999c, Danmole Street, Off Idejo Street, Off Adeola Odeku Street, Victoria Island, Lagos',
  },
  {
    name: 'Access Bank (Diamond)',
    slug: 'access-bank-diamond',
    code: '063',
    ussd: '*426#',
    logo: `${baseUrl}/access-bank-diamond.png`,
    address: 'Plot 1261, Adeola Hopewell Street, Victoria Island, Lagos',
  },
  {
    name: 'ALAT by WEMA',
    slug: 'alat-by-wema',
    code: '035A',
    ussd: '*945*100#',
    logo: `${baseUrl}/alat-by-wema.png`,
    address: 'Wema Towers, 54 Marina, Lagos Island, Lagos',
  },
  {
    name: 'ASO Savings and Loans',
    slug: 'asosavings',
    code: '401',
    ussd: '',
    logo: `${baseUrl}/asosavings.png`,
    address: 'Plot 266 FMBN building, Cadastral Zone A0, Central Business District',
  },
  {
    name: 'Bowen Microfinance Bank',
    slug: 'bowen-microfinance-bank',
    code: '50931',
    ussd: '',
    logo: `${baseUrl}/bowen-microfinance-bank.png`,
    address: 'Baptist Academy Compound, Obanikoro, Ikorodu Road, Lagos State.',
  },
  {
    name: 'CEMCS Microfinance Bank',
    slug: 'cemcs-microfinance-bank',
    code: '50823',
    ussd: '',
    logo: `${baseUrl}/cemcs-microfinance-bank.png`,
    address: '6, Udeco Medical Road, Chevyview Estate, Off Chevron Drive, Lekki, Lagos, Nigeria',
  },
  {
    name: 'Citibank Nigeria',
    slug: 'citibank-nigeria',
    code: '023',
    ussd: '',
    logo: `${baseUrl}/citibank-nigeria.png`,
    address: '27, Kofo Abayomi Street, Victoria Island, Lagos',
  },
  {
    name: 'Ecobank Nigeria',
    slug: 'ecobank-nigeria',
    code: '050',
    ussd: '*326#',
    logo: `${baseUrl}/ecobank-nigeria.png`,
    address: '21, Ahmadu Bello Way, Victoria Island, Lagos',
  },
  {
    name: 'Ekondo Microfinance Bank',
    slug: 'ekondo-microfinance-bank',
    code: '562',
    ussd: '*540*178#',
    logo: `${baseUrl}/ekondo-microfinance-bank.png`,
    address: 'DAVANDY HOUSE 43 Murtala Mohammed Highway, Calabar, Cross River.',
  },
  {
    name: 'Fidelity Bank',
    slug: 'fidelity-bank',
    code: '070',
    ussd: '*770#',
    logo: `${baseUrl}/fidelity-bank.png`,
    address: '2, Kofo Abayomi Street, Victoria Island, Lagos',
  },
  {
    name: 'First Bank of Nigeria',
    slug: 'first-bank-of-nigeria',
    code: '011',
    ussd: '*894#',
    logo: `${baseUrl}/first-bank-of-nigeria.png`,
    address: 'Samuel Asabia House, 35 Marina, Lagos',
  },
  {
    name: 'First City Monument Bank',
    slug: 'first-city-monument-bank',
    code: '214',
    ussd: '*329#',
    logo: `${baseUrl}/first-city-monument-bank.png`,
    address: 'Primose Towers, 17a, Tinubu Street, Lagos',
  },
  {
    name: 'Globus Bank',
    slug: 'globus-bank',
    code: '00103',
    ussd: '*989#',
    logo: `${baseUrl}/globus-bank.png`,
    address: 'Plot 722 Akinbo Savage, Victoria Island, Lagos State',
  },
  {
    name: 'Guaranty Trust Bank',
    slug: 'guaranty-trust-bank',
    code: '058',
    ussd: '*737#',
    logo: `${baseUrl}/guaranty-trust-bank.png`,
    address: '635, Akin Adesola Street, Victoria Island, Lagos',
  },
  {
    name: 'Hasal Microfinance Bank',
    slug: 'hasal-microfinance-bank',
    code: '50383',
    ussd: '*322*127#',
    logo: `${baseUrl}/hasal-mfb.png`,
    address: 'Plot 1652, Ahmadu Bello Way, Garki District, Abuja',
  },
  {
    name: 'Heritage Bank',
    slug: 'heritage-bank',
    code: '030',
    ussd: '*322#',
    logo: `${baseUrl}/heritage-bank.png`,
    address: '292b, Ajose Adeogun Street, Victoria Island, Lagos',
  },
  {
    name: 'Jaiz Bank',
    slug: 'jaiz-bank',
    code: '301',
    ussd: '*389*301#',
    logo: `${baseUrl}/jaiz-bank.png`,
    address: 'Kano House, Plot 73, Ralph Shodeinde Street, Central Business District, Abuja',
  },
  {
    name: 'Keystone Bank',
    slug: 'keystone-bank',
    code: '082',
    ussd: '*7111#',
    logo: `${baseUrl}/keystone-bank.png`,
    address: 'Keystone House, 1, Keystone Crescent, Victoria Island, Lagos',
  },
  {
    name: 'Kuda Bank',
    slug: 'kuda-bank',
    code: '50211',
    ussd: '',
    logo: `${baseUrl}/kuda-bank.png`,
    address: '1-11 Commercial Avenue, Yaba, Lagos, Nigeria',
  },
  {
    name: 'Lotus Bank',
    slug: 'lotus-bank',
    code: '303',
    ussd: '*5045#',
    logo: `${baseUrl}/lotus-bank.png`,
    address: '39C Ahmed Onibudo Street, Victoria Island, Lagos.',
  },
  {
    name: 'Moniepoint MFB',
    slug: 'moniepoint-mfb-ng',
    code: '50515',
    ussd: '*5573#',
    logo: `${baseUrl}/moniepoint-mfb-ng.png`,
    address: 'The Post Square, Off Adeola Odeku, Victoria Island, Lagos, Nigeria',
  },
  {
    name: 'One Finance',
    slug: 'one-finance',
    code: '565',
    ussd: '*1303#',
    logo: `${baseUrl}/one-finance.png`,
    address: 'Plot 642C Adeyemo Alakija St, Victoria Island, Lagos 101241, Lagos, Nigeria',
  },
  {
    name: 'OPay',
    slug: 'paycom',
    code: '999992',
    ussd: '*955#',
    logo: `${baseUrl}/paycom.png`,
    address: 'Alexander House, Plot 9, Dr.Nurudeen Olowopopo Avenue, Alausa, Lagos',
  },
  {
    name: 'Paga',
    slug: 'paga',
    code: '327',
    ussd: '',
    logo: `${baseUrl}/paga.png`,
    address: '176 Herbert Macaulay Road, Yaba, Lagos, Nigeria.',
  },
  {
    name: 'PalmPay',
    slug: 'palmpay',
    code: '999991',
    ussd: '*861#',
    logo: `${baseUrl}/palmpay.png`,
    address: 'Lagos, 20 Opebi Rd, Nigeria',
  },
  {
    name: 'Parallex Bank',
    slug: 'parallex-bank',
    code: '526',
    ussd: '*322*318*0#',
    logo: `${baseUrl}/parallex-bank.png`,
    address: '1261 Adeola Hopewell St, Victoria Island, Lagos, 106104 Lagos State , Nigeria',
  },
  {
    name: 'PayCom',
    slug: 'paycom',
    code: '100004',
    ussd: '*955#',
    logo: `${baseUrl}/paycom.png`,
    address: '242 Kofo Abayomi St, Victoria Island, Lagos 106104, Lagos, Nigeria',
  },
  {
    name: 'Polaris Bank',
    slug: 'polaris-bank',
    code: '076',
    ussd: '*833#',
    logo: `${baseUrl}/polaris-bank.png`,
    address: '20 Akin Adesola St, Victoria Island, Lagos 106104, Lagos, Nigeria',
  },
  {
    name: 'Providus Bank',
    slug: 'providus-bank',
    code: '101',
    ussd: '',
    logo: `${baseUrl}/providus-bank.png`,
    address: '114, Adeola Odeku, Eletu Ogabi Street, Victoria Island,',
  },
  {
    name: 'Rubies MFB',
    slug: 'rubies-mfb',
    code: '125',
    ussd: '*7797#',
    logo: `${baseUrl}/rubies-mfb.png`,
    address: '17B, Akanbi Disu Street, Lekki Phase 1, Lagos',
  },
  {
    name: 'Sparkle Microfinance Bank',
    slug: 'sparkle-microfinance-bank',
    code: '51310',
    ussd: '',
    logo: `${baseUrl}/sparkle-microfinance-bank.png`,
    address: '',
  },
  {
    name: 'Stanbic IBTC Bank',
    slug: 'stanbic-ibtc-bank',
    code: '221',
    ussd: '*909#',
    logo: `${baseUrl}/stanbic-ibtc-bank.png`,
    address: 'IBTC Place, Walter Carrington Crescent, Victoria Island, Lagos',
  },
  {
    name: 'Standard Chartered Bank',
    slug: 'standard-chartered-bank',
    code: '068',
    ussd: '',
    logo: `${baseUrl}/standard-chartered-bank.png`,
    address: '142, Ahmadu Bello Way, Victoria Island, Lagos',
  },
  {
    name: 'Sterling Bank',
    slug: 'sterling-bank',
    code: '232',
    ussd: '*822#',
    logo: `${baseUrl}/sterling-bank.png`,
    address: 'Sterling Towers, 20 Marina, Lagos',
  },
  {
    name: 'Suntrust Bank',
    slug: 'suntrust-bank',
    code: '100',
    ussd: '*5230#',
    logo: `${baseUrl}/suntrust-bank.png`,
    address: '1, Oladele Olashore Street, Victoria Island, Lagos',
  },
  {
    name: 'TAJ Bank',
    slug: 'taj-bank',
    code: '302',
    ussd: '*898#',
    logo: `${baseUrl}/taj-bank.png`,
    address: 'Plot 72 Ahmadu Bello Way, Central Business District, Abuja, Nigeri',
  },
  {
    name: 'TCF MFB',
    slug: 'tcf-mfb',
    code: '51211',
    ussd: '*908#',
    logo: `${baseUrl}/tcf-mfb.png`,
    address: '33, Adeola Hopewell Street, Victoria Island, Lagos',
  },
  {
    name: 'Titan Trust Bank',
    slug: 'titan-trust-bank',
    code: '102',
    ussd: '*922#',
    logo: `${baseUrl}/titan-trust-bank.png`,
    address: 'Plot 1680, Sanusi Fafunwa Street, Victoria Island Lagos',
  },
  {
    name: 'Union Bank of Nigeria',
    slug: 'union-bank-of-nigeria',
    code: '032',
    ussd: '*826#',
    logo: `${baseUrl}/union-bank-of-nigeria.png`,
    address: 'Stallion Plaza, 36 Marina, Lagos',
  },
  {
    name: 'United Bank For Africa',
    slug: 'united-bank-for-africa',
    code: '033',
    ussd: '*919#',
    logo: `${baseUrl}/united-bank-for-africa.png`,
    address: '57 Marina, Lagos',
  },
  {
    name: 'Unity Bank',
    slug: 'unity-bank',
    code: '215',
    ussd: '*7799#',
    logo: `${baseUrl}/unity-bank.png`,
    address: 'Plot 785, Herbert Macaulay Way, Central Business District, Abuja',
  },
  {
    name: 'VFD',
    slug: 'vfd',
    code: '566',
    ussd: '',
    logo: `${baseUrl}/vfd.png`,
    address: '214 Broad Street, Marina, Lagos Nigeria',
  },
  {
    name: 'Wema Bank',
    slug: 'wema-bank',
    code: '035',
    ussd: '*945#',
    logo: `${baseUrl}/wema-bank.png`,
    address: 'Wema Towers, 54 Marina, Lagos Island, Lagos',
  },
  {
    name: 'Zenith Bank',
    slug: 'zenith-bank',
    code: '057',
    ussd: '*966#',
    logo: `${baseUrl}/zenith-bank.png`,
    address: 'Plot 84, Ajose Adeogun Street, Victoria Island, Lagos',
  },
];